### ISSUE TITLE
Fix head tag

### ISSUE THREAD

**Issue by Ritesh-Dabral** [Stormshadows/food-delivery-app#2]
Hi, 
I am new to hactoberfest event  and want to contribute to your application. If there is any issue that you can assign me, I would love to work on that. I saw, fav icon missing from your application and title shows 'React App'. If that is not an issue, I would like to fix that and start conributing to your project.
Thanks and Regards
Ritesh
![image](https://user-images.githubusercontent.com/36252036/193495572-18c589ef-9e08-4bc5-90f5-cf5f72362aa3.png)

**Comment by Stormshadows** [comment]
sure go ahead
